### PR TITLE
Pull for May 30, 2020 for Jean June 1 requests

### PR DESCRIPTION
**Pull request by lmaaronson**

### CODE REVIEW

**Comment by lmaaronson** [comment]
That is not the correct merge...

laurie

**Comment by wernerglinka** [comment]
There where several old pull requests. I am cleaning up the list. The latest one still has conflicts. You need to fix that before I can merge it.


Werner Glinka
***@***.***
650 867 0778

**Comment by lmaaronson** [comment]
How do I fix the conflicts

la

**Comment by wernerglinka** [comment]
I don't know. That depends on what you edited/changed. Have a look at the pull request page. It says 




Werner Glinka
***@***.***
650 867 0778

**Comment by lmaaronson** [comment]
I guess my question is how to I fix it in github or back locally.

also I need to change the position of the tag line on the home (index)
page.  is it simple enough to change the CSS code.

laurie

**Comment by wernerglinka** [comment]
There are conflicts in a file called npm-shrinkwrap.json. You'll need to look at the file and resolve these conflicts. Unfortunately, I am too busy at this point to have a look. I might be able to do so next week... maybe.


Werner Glinka
***@***.***
650 867 0778

**Comment by lmaaronson** [comment]
I think I fixed issues.

laurie

**Comment by wernerglinka** [comment]
What does it say on the pull request page? Looks like the issue is still there:  https://github.com/wernerglinka/codesavvy/pull/12


Werner Glinka
***@***.***
650 867 0778

**Pull request merged**
